# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdec5caf86843143a1ddb3fbf7fe64549585881642906ea2be9e33c47927f1c50e5b561bee62e5e2f3ba126faf9f0856c3e0c25c744861a76d9d6f4bd2212191

test:
  secret_key_base: ef0fd841ad23ac9000874e203ad26ac864f0c500366fea868e6af13a50f1fb183e56b2aec109c6b27531b0c62e60dd8d72153f201f39450b621afced94cde680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
